### ISSUE TITLE
connection termination

### ISSUE THREAD

**Issue by binarytracer** [quentinadam/node-mysql-promise-wrapper#2]
how to terminate the connection?

```js

import Database from 'mysql-promise-wrapper';

(async function(){
     let database = new Database({ ... config here... });
    

  // 1 await database.close(); 
  // 2 await database.end();
 //  3 await database.destroy();

});
 
```

ive tried those options like this, but it seems i got same conclusion **function no found**.

**Comment by quentinadam** [comment]
For the moment, a connection pool is created by the Database object, and connections are automatically managed by the pool.

When using the `query` function directly, a new/available connection is asked to the pool, the query is executed and then the connection is returned to the pool.

```
database.query("SELECT * FROM items WHERE property = ?", ["value"]).then((rows) => {
    console.log(rows);
});
```

When using the `connection` function, the function expects a function as argument that returns a promise. Before the promise-generating function is called, a new/available connection is asked to the pool, the the promise -generating function is called with that connection, and then the connection is returned to the pool.

database.connection((connection) => {
    return connection.query("SELECT * FROM items WHERE property = ?", ["value"])
}).then((rows) => {
    console.log(rows);
});

As such, as this library is using a connection pool, there is no need to close the connections, as they are managed by the pool.

I hope this helps.

**Comment by binarytracer** [comment]
yeah thanks, sorry i was very late on confirming.
